apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: nginx-config-variables
    envs:
      - config-with-variables.env
    behavior: merge
  - name: nginx-config-static
    envs:
      - config.env
    behavior: merge
