apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomize-config-configmap.yaml

resources:
  - deployment.yaml

configMapGenerator:
  - name: nginx-config
    envs:
      - config.env

vars:
  - name: BASE_URL
    objref:
      kind: ConfigMap
      name: nginx-config
      apiVersion: v1
    fieldref:
      fieldpath: data.BASE_URL
